autoInstallPeers: true

ignoredBuiltDependencies:
  - '@swc/core'
  - canvas
  - less
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - nx
  - prisma
