FROM alpine:3.19

RUN apk add --no-cache \
    tesseract-ocr \
    tesseract-ocr-data-spa \
    tesseract-ocr-data-eng

# Create directories for input/output
RUN mkdir -p /input /output

WORKDIR /input

# Keep container running
CMD ["tail", "-f", "/dev/null"]
